package todoListController;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class MainLoginController {
	@FXML
	private AnchorPane LoginInerface;
	@FXML
	private TextField username_txt;
	@FXML
	private TextField password_txt;
	@FXML
	private Button login_btn;
	@FXML
	private Button signUp_btn;

	// Event Listener on Button[#login_btn].onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#signUp_btn].onAction
	@FXML
	public void signUp(ActionEvent event) {
		// TODO Autogenerated
	}
}
