package todoListController;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class MainSignUpController {
	@FXML
	private TextField username_txt;
	@FXML
	private TextField password_btn;
	@FXML
	private TextField confirmPass_btn;
	@FXML
	private Button createAccount_btn;

	// Event Listener on Button[#createAccount_btn].onAction
	@FXML
	public void createAccount(ActionEvent event) {
		// TODO Autogenerated
	}
}
