package todoListController;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;
import todoListDaoImpl.TodoListDaoImpl;
import todoListEntity.TodoList;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class TodoHomeController {
	@FXML
	private AnchorPane mainHome;
	@FXML
	private Button addTask_btn;
	@FXML
	private Button showTask_btn;
	@FXML
	private Button updateTask_btn;
	@FXML
	private Button deleteTask_btn;
	@FXML
	private Button refresh_btn;
	@FXML
	private TextField taskId_txt;
	@FXML
	private TextField title_txt;
	@FXML
	private TextField status_txt;
	@FXML
	private TextField deadline_txt;
	@FXML
	private TextField description_txt;
	@FXML
	private TextField categoryId_txt;
	@FXML
	private TableView<TodoList> table;
	@FXML
	private TableColumn<TodoList, Integer> taskId_col;
	@FXML
	private TableColumn<TodoList, String> title_col;
	@FXML
	private TableColumn<TodoList, String> description_col;
	@FXML
	private TableColumn<TodoList, String> status_col;
	@FXML
	private TableColumn<TodoList, String> deadline_col;
	@FXML
	private TableColumn<TodoList, Integer> category_col;
	
	TodoListDaoImpl list = new TodoListDaoImpl();

	// Event Listener on Button[#addTask_btn].onAction
	@FXML
	public void addTask(ActionEvent event) {
//		list.createTodoList (
//				taskId_txt.getText(),
//				title_txt.getText(),
//				status_txt.getText(),
//				deadline_txt.getText(),
//				description_txt.getText(),
//				categoryId_txt.getText());
//		
//		Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
//		alert.setTitle("Student Registration");
//		
//		alert.setHeaderText("Student Registration");
//		alert.setContentText("Student Added Successfully");
//		
//		alert.showAndWait();
//		
//		showStudents();
	}
	// Event Listener on Button[#showTask_btn].onAction
	@FXML
	public void showTask(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#updateTask_btn].onAction
	@FXML
	public void updateTask(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteTask_btn].onAction
	@FXML
	public void DeleteTask(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#refresh_btn].onAction
	@FXML
	public void refresh(ActionEvent event) {
		// TODO Autogenerated
	}
}
